# Generated by Django 2.2.7 on 2019-11-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todos_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('deadline_date', models.DateField(auto_now_add=True)),
                ('todos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoItem', to='todos.Todos')),
            ],
            options={
                'ordering': ['deadline_date'],
            },
        ),
    ]
